### ISSUE TITLE
Highlight text in response/request

### ISSUE THREAD

**Issue by theblackturtle** [chopicalqui/TurboDataMiner#2]
Hi, Thanks for creating this awesome extension. 
It would be nice if it has an API that can highlight text in the request/response. This can help for identity where the matching text in the request/response easier.

**Comment by chopicalqui** [comment]
@theblackturtle Thanks for your feedback.

In theory, it should be possible already but somehow I am not able to successfully apply markers via Burp Suite's API function [callbacks.applyMarkers](https://portswigger.net/burp/extender/api/burp/IBurpExtenderCallbacks.html#applyMarkers(burp.IHttpRequestResponse,%20java.util.List,%20java.util.List)). Maybe you know how it works.

Below you'll find a script, which you could execute in the _Proxy History Analyzer_. It should highlight the HTTP request header _Host_ in all in-scope requests (but somehow it does not). Note, if applying markers via function _applyMarkers_ works, then the highlighted text would not be displayed in Turbo Data Miner's _Message Information_ tab but in the _Highlights_ tab (see screenshot), which can be dynamically added to the Turbo Data Miner GUI by adding the _IHttpRequestResponseWithMarkers_ object to the _message_infos_ dictionary (see code below).
![image](https://user-images.githubusercontent.com/39760194/85627457-ccfcd180-b66e-11ea-8772-769c2bc2e694.png)

The script also prints debugging information to standard output at the end of the script, which confirms that no markers are applied by the _applyMarkers_ function. At the moment, I don't know why this happens.

```
from array import array
import re
# Do the initial setup
if ref == 1 or "regex" not in session:
	session["regex"] = re.compile("^Host: .*$", re.IGNORECASE | re.MULTILINE)
	header = ["URL"]
# Process only in-scope HTTP responses
if in_scope:
	markers = []
	# Find host header marker positions 
	for item in session["regex"].finditer(helpers.bytesToString(message_info.getRequest())):
		markers.append(array('i', [item.start(), item.end()]))
	# Create new message info with markers
	if markers:
		message_infos = {"Hightlights": callbacks.applyMarkers(message_info, markers, None)}
		rows = [[url]]
		# Debugging: The newly created request/response item does not contain markers
		# https://forum.portswigger.net/thread/imessageeditor-does-not-show-markers-47a608c2
		try:
			print(markers)
			print(helpers.bytesToString(message_info_marker.getRequest()))
		except:
			print("Cannot print debug information")
```

**Comment by theblackturtle** [comment]
@chopicalqui, It seems this `applyMarkers` only working when using with `ScanIssue`. Can we wrap it into `ScanIssue`?

**Comment by chopicalqui** [comment]
@theblackturtle, I think there is an issue with the method `applyMarkers` (maybe I am using it incorrectly). Therefore, I added an additional post to the following thread:
https://forum.portswigger.net/thread/imessageeditor-does-not-show-markers-47a608c2

Based on this thread, markers should be displayed in `IMessageEditor` components and then, there is no need for `ScanIssues`.

I hope PortSwigger can provide a solution and then I am able to update my above script to support highlighting.

**Comment by chopicalqui** [comment]
@theblackturtle I received feedback from PortSwigger:

> As mentioned in the documentation, "Markers are used in various situations, such as specifying Intruder payload positions, Scanner insertion points, and highlights in Scanner issues". Unfortunately, this does not include being displayed in the editor.
> 
> This is because the markers are not a part of the byte array that has been passed to the message editor.

As a result, we can only use scan issues (as you suggested) to highlight text in requests/responses. Therefore, below you will find a Turbo Data Miner script example, which creates a scan issue for every HTTP request/response item that contains the HTTP response header `Server`. Thereby, it highlights the server header.

```
from array import array
import re, difflib, os
from burp import IScanIssue

class CustomScanIssue (IScanIssue):
	"""
	Class implements IScanIssue to hold custom scan issue details
	"""
	
	def __init__(self, httpService, url, httpMessages, name, detail, severity):
		self._httpService = httpService
		self._url = url
		self._httpMessages = httpMessages
		self._name = name
		self._detail = detail
		self._severity = severity
	
	def getUrl(self):
		return self._url

	def getIssueName(self):
		return self._name

	def getIssueType(self):
		return 0

	def getSeverity(self):
		return self._severity

	def getConfidence(self):
		return "Certain"

	def getIssueBackground(self):
		pass

	def getRemediationBackground(self):
		pass

	def getIssueDetail(self):
		return self._detail

	def getRemediationDetail(self):
		pass

	def getHttpMessages(self):
		return self._httpMessages

	def getHttpService(self):
		return self._httpService

# Do the initial setup and compile regular expression
if ref == 1 or "regex" not in session:
	session["regex"] = re.compile("^Server: .*$", re.IGNORECASE | re.MULTILINE)
	header = ["URL"]
# Process only in-scope HTTP responses
if in_scope:
	# Find server header marker positions and store them in array markers
	markers = []
	for item in session["regex"].finditer(helpers.bytesToString(message_info.getResponse())):
		markers.append(array('i', [item.start(), item.end()]))
	# Create new scan issue and apply markers on identified HTTP response headers Server 
	if markers:
		message_info_marker = callbacks.applyMarkers(message_info, None, markers)
		callbacks.addScanIssue(CustomScanIssue(message_info.getHttpService(),
			helpers.analyzeRequest(message_info).getUrl(),
			[message_info_marker],
			"HTTP Request Header Server",
			"The response contains HTTP Request Header Server",
			"Information"))
```
You can use this script as a starting point and customise it according to your needs.

Personally, I would be careful using scan issues to highlight text because once a scan issue is created you cannot deleted it anymore. In addition, with each execution of this script, new scan issues are added to the scan issue list. Therefore, the scan issue list can become very messy.

Due to this reasons, this script won't become part of the Turbo Data Miner app.
