### ISSUE TITLE
Detect the end of the process

### ISSUE THREAD

**Issue by theblackturtle** [chopicalqui/TurboDataMiner#3]
Hi, Are there any variables to detect the end of the process? Like at the beginning of the process, the `ref == 1` used to detect that is the first request.

Thanks.

**Comment by chopicalqui** [comment]
@theblackturtle Yes there is. You can use variable `row_count` for this. Refer to Turbo Data Miner's _About_ tab for more information. Below you will find a short script, which illustrates how you could use `row_count`:
```
if ref == 1:
	header = ["Ref.", "URL"]
if ref == row_count:
	rows = [[ref, str(url)]]
```
This script only adds the last request/response item to the table.
